{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Install packages if not"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: numpy in /usr/local/lib/python3.8/site-packages (1.19.4)\n",
      "Collecting scipy\n",
      "  Using cached scipy-1.5.4.tar.gz (25.2 MB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h    Preparing wheel metadata ... \u001b[?25lerror\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/opt/python@3.8/bin/python3.8 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/tmp_8dm05__\n",
      "         cwd: /private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-install-z6r4wge6/scipy\n",
      "    Complete output (139 lines):\n",
      "    lapack_opt_info:\n",
      "    lapack_mkl_info:\n",
      "    customize UnixCCompiler\n",
      "      libraries mkl_rt not found in ['/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    openblas_lapack_info:\n",
      "    customize UnixCCompiler\n",
      "    customize UnixCCompiler\n",
      "      libraries openblas not found in ['/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    openblas_clapack_info:\n",
      "    customize UnixCCompiler\n",
      "    customize UnixCCompiler\n",
      "      libraries openblas,lapack not found in ['/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    flame_info:\n",
      "    customize UnixCCompiler\n",
      "      libraries flame not found in ['/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_3_10_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries tatlas,tatlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries tatlas,tatlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries tatlas,tatlas not found in /usr/lib\n",
      "    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_3_10_info:\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries satlas,satlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries satlas,satlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries satlas,satlas not found in /usr/lib\n",
      "    <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in /usr/lib\n",
      "    <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_info:\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in /usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in /usr/local/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack_atlas not found in /usr/lib\n",
      "    customize UnixCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in /usr/lib\n",
      "    <class 'numpy.distutils.system_info.atlas_info'>\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    accelerate_info:\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    lapack_info:\n",
      "    customize UnixCCompiler\n",
      "      libraries lapack not found in ['/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    lapack_src_info:\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-modern-metadata-2hdz0y9y'), proceeding with generating Cython sources and expanding templates\n",
      "      warnings.warn(\"Unrecognized setuptools command ('{}'), proceeding with \"\n",
      "    Running from SciPy source directory.\n",
      "    /private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-build-env-kxbs3l2k/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:\n",
      "        Lapack (http://www.netlib.org/lapack/) libraries not found.\n",
      "        Directories to search for the libraries can be specified in the\n",
      "        numpy/distutils/site.cfg file (section [lapack]) or by setting\n",
      "        the LAPACK environment variable.\n",
      "      if getattr(self, '_calc_info_{}'.format(lapack))():\n",
      "    /private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-build-env-kxbs3l2k/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:\n",
      "        Lapack (http://www.netlib.org/lapack/) sources not found.\n",
      "        Directories to search for the sources can be specified in the\n",
      "        numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n",
      "        the LAPACK_SRC environment variable.\n",
      "      if getattr(self, '_calc_info_{}'.format(lapack))():\n",
      "    Traceback (most recent call last):\n",
      "      File \"/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py\", line 280, in <module>\n",
      "        main()\n",
      "      File \"/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py\", line 263, in main\n",
      "        json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "      File \"/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py\", line 133, in prepare_metadata_for_build_wheel\n",
      "        return hook(metadata_directory, config_settings)\n",
      "      File \"/private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-build-env-kxbs3l2k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py\", line 161, in prepare_metadata_for_build_wheel\n",
      "        self.run_setup()\n",
      "      File \"/private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-build-env-kxbs3l2k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py\", line 253, in run_setup\n",
      "        super(_BuildMetaLegacyBackend,\n",
      "      File \"/private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-build-env-kxbs3l2k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py\", line 145, in run_setup\n",
      "        exec(compile(code, __file__, 'exec'), locals())\n",
      "      File \"setup.py\", line 583, in <module>\n",
      "        setup_package()\n",
      "      File \"setup.py\", line 579, in setup_package\n",
      "        setup(**metadata)\n",
      "      File \"/private/var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/pip-build-env-kxbs3l2k/overlay/lib/python3.8/site-packages/numpy/distutils/core.py\", line 137, in setup\n",
      "        config = configuration()\n",
      "      File \"setup.py\", line 477, in configuration\n",
      "        raise NotFoundError(msg)\n",
      "    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[31mERROR: Command errored out with exit status 1: /usr/local/opt/python@3.8/bin/python3.8 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/z8/54y9sdpn3w57hb5hp_yr_08h0000gn/T/tmp_8dm05__ Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25h"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install numpy scipy pandas"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Real Imports here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "stuff = pd.read_csv(\".\\google_review_ratings.csv\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
